// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
`

type CreateApplicationParams struct {
	GrantWriterID uuid.UUID         `json:"grant_writer_id"`
	GrantID       uuid.UUID         `json:"grant_id"`
	ClientID      uuid.UUID         `json:"client_id"`
	Title         string            `json:"title"`
	Status        ApplicationStatus `json:"status"`
	IsExclusive   bool              `json:"is_exclusive"`
	PublishedAt   sql.NullTime      `json:"published_at"`
	Notes         sql.NullString    `json:"notes"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.GrantWriterID,
		arg.GrantID,
		arg.ClientID,
		arg.Title,
		arg.Status,
		arg.IsExclusive,
		arg.PublishedAt,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.GrantID,
		&i.ClientID,
		&i.Title,
		&i.Status,
		&i.IsExclusive,
		&i.PublishedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
UPDATE applications
SET deleted_at = NOW()
WHERE deleted_at IS NULL
AND grant_writer_id = $1
AND id = $2
`

type DeleteApplicationParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, arg.GrantWriterID, arg.ID)
	return err
}

const getAllApplicationsByClientID = `-- name: GetAllApplicationsByClientID :many
SELECT id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
FROM applications
WHERE deleted_at IS NULL
AND grant_writer_id = $1
AND client_id = $2
`

type GetAllApplicationsByClientIDParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ClientID      uuid.UUID `json:"client_id"`
}

func (q *Queries) GetAllApplicationsByClientID(ctx context.Context, arg GetAllApplicationsByClientIDParams) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getAllApplicationsByClientID, arg.GrantWriterID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.GrantWriterID,
			&i.GrantID,
			&i.ClientID,
			&i.Title,
			&i.Status,
			&i.IsExclusive,
			&i.PublishedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllApplicationsByUserID = `-- name: GetAllApplicationsByUserID :many
SELECT id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
FROM applications
WHERE deleted_at IS NULL
AND grant_writer_id = $1
`

func (q *Queries) GetAllApplicationsByUserID(ctx context.Context, grantWriterID uuid.UUID) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, getAllApplicationsByUserID, grantWriterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.GrantWriterID,
			&i.GrantID,
			&i.ClientID,
			&i.Title,
			&i.Status,
			&i.IsExclusive,
			&i.PublishedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
FROM applications
WHERE deleted_at IS NULL
AND grant_writer_id = $1
and id = $2
`

type GetApplicationByIDParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, arg.GrantWriterID, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.GrantID,
		&i.ClientID,
		&i.Title,
		&i.Status,
		&i.IsExclusive,
		&i.PublishedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const publishApplication = `-- name: PublishApplication :one
UPDATE applications
SET 
  published_at = now()
WHERE deleted_at IS NULL
AND published_at IS NULL
AND grant_writer_id = $1
AND id = $2
RETURNING id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
`

type PublishApplicationParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) PublishApplication(ctx context.Context, arg PublishApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, publishApplication, arg.GrantWriterID, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.GrantID,
		&i.ClientID,
		&i.Title,
		&i.Status,
		&i.IsExclusive,
		&i.PublishedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET
  title = $3,
  status = $4,
  is_exclusive = $5,
  notes = $6,
  updated_at = NOW()
WHERE deleted_at IS NULL
AND id = $1
AND grant_writer_id = $2
RETURNING id, grant_writer_id, grant_id, client_id, title, status, is_exclusive, published_at, notes, created_at, updated_at, deleted_at
`

type UpdateApplicationParams struct {
	ID            uuid.UUID         `json:"id"`
	GrantWriterID uuid.UUID         `json:"grant_writer_id"`
	Title         string            `json:"title"`
	Status        ApplicationStatus `json:"status"`
	IsExclusive   bool              `json:"is_exclusive"`
	Notes         sql.NullString    `json:"notes"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplication,
		arg.ID,
		arg.GrantWriterID,
		arg.Title,
		arg.Status,
		arg.IsExclusive,
		arg.Notes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.GrantID,
		&i.ClientID,
		&i.Title,
		&i.Status,
		&i.IsExclusive,
		&i.PublishedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
