// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, grant_writer_id, contact_name, contact_phone, contact_email, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, grant_writer_id, name, contact_name, contact_phone, contact_email, notes, created_at, updated_at, deleted_at
`

type CreateClientParams struct {
	Name          string         `json:"name"`
	GrantWriterID uuid.UUID      `json:"grant_writer_id"`
	ContactName   sql.NullString `json:"contact_name"`
	ContactPhone  sql.NullString `json:"contact_phone"`
	ContactEmail  sql.NullString `json:"contact_email"`
	Notes         sql.NullString `json:"notes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.Name,
		arg.GrantWriterID,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Notes,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients
SET deleted_at = NOW()
WHERE grant_writer_id = $1
AND id=$2
AND deleted_at IS NULL
`

type DeleteClientParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.ExecContext(ctx, deleteClient, arg.GrantWriterID, arg.ID)
	return err
}

const getAllClientsByGrantWriter = `-- name: GetAllClientsByGrantWriter :many
SELECT id, grant_writer_id, name, contact_name, contact_phone, contact_email, notes, created_at, updated_at, deleted_at
FROM clients
WHERE grant_writer_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetAllClientsByGrantWriter(ctx context.Context, grantWriterID uuid.UUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getAllClientsByGrantWriter, grantWriterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.GrantWriterID,
			&i.Name,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, grant_writer_id, name, contact_name, contact_phone, contact_email, notes, created_at, updated_at, deleted_at
FROM clients
WHERE grant_writer_id = $1
AND id = $2
AND deleted_at IS NULL
`

type GetClientByIDParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) GetClientByID(ctx context.Context, arg GetClientByIDParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, arg.GrantWriterID, arg.ID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET 
  name = $2,
  contact_name = $3,
  contact_phone = $4,
  contact_email = $5,
  notes = $6,
  updated_at = NOW()
where id = $7
AND grant_writer_id = $1
AND deleted_at IS NULL
RETURNING id, grant_writer_id, name, contact_name, contact_phone, contact_email, notes, created_at, updated_at, deleted_at
`

type UpdateClientParams struct {
	GrantWriterID uuid.UUID      `json:"grant_writer_id"`
	Name          string         `json:"name"`
	ContactName   sql.NullString `json:"contact_name"`
	ContactPhone  sql.NullString `json:"contact_phone"`
	ContactEmail  sql.NullString `json:"contact_email"`
	Notes         sql.NullString `json:"notes"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.GrantWriterID,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Notes,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
