// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grants.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDeadline = `-- name: CreateDeadline :one
INSERT INTO grant_deadlines (grant_id, label, date, description)
VALUES ($1, $2, $3, $4)
RETURNING id, grant_id, label, date, description, created_at
`

type CreateDeadlineParams struct {
	GrantID     uuid.UUID         `json:"grant_id"`
	Label       GrantDeadlineType `json:"label"`
	Date        time.Time         `json:"date"`
	Description sql.NullString    `json:"description"`
}

func (q *Queries) CreateDeadline(ctx context.Context, arg CreateDeadlineParams) (GrantDeadline, error) {
	row := q.db.QueryRowContext(ctx, createDeadline,
		arg.GrantID,
		arg.Label,
		arg.Date,
		arg.Description,
	)
	var i GrantDeadline
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Label,
		&i.Date,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO grants (grant_writer_id, title, funder_name, visibility, funder_website, description, award_amount_min, award_amount_max, eligibility_notes, estimated_application_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, grant_writer_id, title, funder_name, funder_website, description, award_amount_min, award_amount_max, eligibility_notes, estimated_application_hours, visibility, created_at, updated_at, deleted_at
`

type CreateGrantParams struct {
	GrantWriterID             uuid.UUID       `json:"grant_writer_id"`
	Title                     string          `json:"title"`
	FunderName                string          `json:"funder_name"`
	Visibility                GrantVisibility `json:"visibility"`
	FunderWebsite             sql.NullString  `json:"funder_website"`
	Description               sql.NullString  `json:"description"`
	AwardAmountMin            sql.NullString  `json:"award_amount_min"`
	AwardAmountMax            sql.NullString  `json:"award_amount_max"`
	EligibilityNotes          sql.NullString  `json:"eligibility_notes"`
	EstimatedApplicationHours sql.NullString  `json:"estimated_application_hours"`
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error) {
	row := q.db.QueryRowContext(ctx, createGrant,
		arg.GrantWriterID,
		arg.Title,
		arg.FunderName,
		arg.Visibility,
		arg.FunderWebsite,
		arg.Description,
		arg.AwardAmountMin,
		arg.AwardAmountMax,
		arg.EligibilityNotes,
		arg.EstimatedApplicationHours,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Title,
		&i.FunderName,
		&i.FunderWebsite,
		&i.Description,
		&i.AwardAmountMin,
		&i.AwardAmountMax,
		&i.EligibilityNotes,
		&i.EstimatedApplicationHours,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDeadline = `-- name: DeleteDeadline :exec
DELETE FROM grant_deadlines gd
USING grants g
WHERE g.id= gd.grant_id
AND gd.grant_id = $2
AND g.grant_writer_id = $1
AND gd.id = $3
AND g.deleted_at IS NULL
`

type DeleteDeadlineParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	GrantID       uuid.UUID `json:"grant_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteDeadline(ctx context.Context, arg DeleteDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeadline, arg.GrantWriterID, arg.GrantID, arg.ID)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
UPDATE grants
SET deleted_at = NOW()
WHERE grant_writer_id = $1
AND id = $2
AND deleted_at IS NULL
`

type DeleteGrantParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) DeleteGrant(ctx context.Context, arg DeleteGrantParams) error {
	_, err := q.db.ExecContext(ctx, deleteGrant, arg.GrantWriterID, arg.ID)
	return err
}

const getAllGrants = `-- name: GetAllGrants :many
SELECT id, grant_writer_id, title, funder_name, funder_website, description, award_amount_min, award_amount_max, eligibility_notes, estimated_application_hours, visibility, created_at, updated_at, deleted_at
FROM grants
WHERE grant_writer_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetAllGrants(ctx context.Context, grantWriterID uuid.UUID) ([]Grant, error) {
	rows, err := q.db.QueryContext(ctx, getAllGrants, grantWriterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grant
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.GrantWriterID,
			&i.Title,
			&i.FunderName,
			&i.FunderWebsite,
			&i.Description,
			&i.AwardAmountMin,
			&i.AwardAmountMax,
			&i.EligibilityNotes,
			&i.EstimatedApplicationHours,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeadlinesByGrantID = `-- name: GetDeadlinesByGrantID :many
SELECT gd.id, grant_id, label, date, gd.description, gd.created_at
FROM grant_deadlines gd
JOIN grants g ON g.id = gd.grant_id
WHERE gd.grant_id = $2
AND g.grant_writer_id = $1
AND g.deleted_at IS NULL
`

type GetDeadlinesByGrantIDParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	GrantID       uuid.UUID `json:"grant_id"`
}

func (q *Queries) GetDeadlinesByGrantID(ctx context.Context, arg GetDeadlinesByGrantIDParams) ([]GrantDeadline, error) {
	rows, err := q.db.QueryContext(ctx, getDeadlinesByGrantID, arg.GrantWriterID, arg.GrantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrantDeadline
	for rows.Next() {
		var i GrantDeadline
		if err := rows.Scan(
			&i.ID,
			&i.GrantID,
			&i.Label,
			&i.Date,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrantByID = `-- name: GetGrantByID :one
SELECT id, grant_writer_id, title, funder_name, funder_website, description, award_amount_min, award_amount_max, eligibility_notes, estimated_application_hours, visibility, created_at, updated_at, deleted_at
FROM grants
WHERE grant_writer_id = $1
AND id = $2
AND deleted_at IS NULL
`

type GetGrantByIDParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) GetGrantByID(ctx context.Context, arg GetGrantByIDParams) (Grant, error) {
	row := q.db.QueryRowContext(ctx, getGrantByID, arg.GrantWriterID, arg.ID)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Title,
		&i.FunderName,
		&i.FunderWebsite,
		&i.Description,
		&i.AwardAmountMin,
		&i.AwardAmountMax,
		&i.EligibilityNotes,
		&i.EstimatedApplicationHours,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateGrant = `-- name: UpdateGrant :one
UPDATE grants
set
  title = $3,
  funder_name = $4,
  visibility = $5,
  funder_website = $6,
  description = $7,
  award_amount_min = $8,
  award_amount_max = $9,
  eligibility_notes = $10,
  estimated_application_hours = $11,
  updated_at = NOW()
WHERE grant_writer_id = $1
AND  id = $2
AND deleted_at IS NULL
RETURNING id, grant_writer_id, title, funder_name, funder_website, description, award_amount_min, award_amount_max, eligibility_notes, estimated_application_hours, visibility, created_at, updated_at, deleted_at
`

type UpdateGrantParams struct {
	GrantWriterID             uuid.UUID       `json:"grant_writer_id"`
	ID                        uuid.UUID       `json:"id"`
	Title                     string          `json:"title"`
	FunderName                string          `json:"funder_name"`
	Visibility                GrantVisibility `json:"visibility"`
	FunderWebsite             sql.NullString  `json:"funder_website"`
	Description               sql.NullString  `json:"description"`
	AwardAmountMin            sql.NullString  `json:"award_amount_min"`
	AwardAmountMax            sql.NullString  `json:"award_amount_max"`
	EligibilityNotes          sql.NullString  `json:"eligibility_notes"`
	EstimatedApplicationHours sql.NullString  `json:"estimated_application_hours"`
}

func (q *Queries) UpdateGrant(ctx context.Context, arg UpdateGrantParams) (Grant, error) {
	row := q.db.QueryRowContext(ctx, updateGrant,
		arg.GrantWriterID,
		arg.ID,
		arg.Title,
		arg.FunderName,
		arg.Visibility,
		arg.FunderWebsite,
		arg.Description,
		arg.AwardAmountMin,
		arg.AwardAmountMax,
		arg.EligibilityNotes,
		arg.EstimatedApplicationHours,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Title,
		&i.FunderName,
		&i.FunderWebsite,
		&i.Description,
		&i.AwardAmountMin,
		&i.AwardAmountMax,
		&i.EligibilityNotes,
		&i.EstimatedApplicationHours,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
