// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddTopicToClient(ctx context.Context, arg AddTopicToClientParams) (int64, error)
	AddTopicToGrant(ctx context.Context, arg AddTopicToGrantParams) (int64, error)
	CountValidTokens(ctx context.Context, grantWriterID uuid.UUID) (int64, error)
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateDeadline(ctx context.Context, arg CreateDeadlineParams) (GrantDeadline, error)
	CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRefreshTokens(ctx context.Context, grantWriterID uuid.UUID) error
	DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteClientTopic(ctx context.Context, arg DeleteClientTopicParams) error
	DeleteDeadline(ctx context.Context, arg DeleteDeadlineParams) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteGrant(ctx context.Context, arg DeleteGrantParams) error
	DeleteGrantTopic(ctx context.Context, arg DeleteGrantTopicParams) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteTopic(ctx context.Context, arg DeleteTopicParams) error
	GetAllApplicationsByClientID(ctx context.Context, arg GetAllApplicationsByClientIDParams) ([]Application, error)
	GetAllApplicationsByUserID(ctx context.Context, grantWriterID uuid.UUID) ([]Application, error)
	GetAllClientsByGrantWriter(ctx context.Context, grantWriterID uuid.UUID) ([]Client, error)
	GetAllGrants(ctx context.Context, grantWriterID uuid.UUID) ([]Grant, error)
	GetAllTopics(ctx context.Context, grantWriterID uuid.UUID) ([]GetAllTopicsRow, error)
	GetAllTopicsByClient(ctx context.Context, arg GetAllTopicsByClientParams) ([]GetAllTopicsByClientRow, error)
	GetAllTopicsByGrant(ctx context.Context, arg GetAllTopicsByGrantParams) ([]GetAllTopicsByGrantRow, error)
	GetApplicationByID(ctx context.Context, arg GetApplicationByIDParams) (Application, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (Client, error)
	GetDeadlinesByGrantID(ctx context.Context, arg GetDeadlinesByGrantIDParams) ([]GrantDeadline, error)
	GetGrantByID(ctx context.Context, arg GetGrantByIDParams) (Grant, error)
	GetRefreshTokenByTokenValue(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	PublishApplication(ctx context.Context, arg PublishApplicationParams) (Application, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateGrant(ctx context.Context, arg UpdateGrantParams) (Grant, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (UpdateTopicRow, error)
}

var _ Querier = (*Queries)(nil)
