// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateDeadline(ctx context.Context, arg CreateDeadlineParams) (GrantDeadline, error)
	CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteDeadline(ctx context.Context, arg DeleteDeadlineParams) error
	DeleteGrant(ctx context.Context, arg DeleteGrantParams) error
	GetAllClientsByGrantWriter(ctx context.Context, grantWriterID uuid.UUID) ([]Client, error)
	GetAllGrants(ctx context.Context, grantWriterID uuid.UUID) ([]Grant, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (Client, error)
	GetDeadlinesByGrantID(ctx context.Context, arg GetDeadlinesByGrantIDParams) ([]GrantDeadline, error)
	GetGrantByID(ctx context.Context, arg GetGrantByIDParams) (Grant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateGrant(ctx context.Context, arg UpdateGrantParams) (Grant, error)
	UpdateLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
