// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countValidTokens = `-- name: CountValidTokens :one
SELECT count(*)
FROM refresh_tokens
WHERE grant_writer_id = $1
AND expires_at > NOW()
`

func (q *Queries) CountValidTokens(ctx context.Context, grantWriterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValidTokens, grantWriterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens (grant_writer_id, token, user_agent, ip_address)
VALUES ($1, $2, $3, $4)
RETURNING id, grant_writer_id, token, user_agent, ip_address, created_at, expires_at
`

type CreateTokenParams struct {
	GrantWriterID uuid.UUID      `json:"grant_writer_id"`
	Token         string         `json:"token"`
	UserAgent     sql.NullString `json:"user_agent"`
	IpAddress     pqtype.Inet    `json:"ip_address"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.GrantWriterID,
		arg.Token,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Token,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllRefreshTokens = `-- name: DeleteAllRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE grant_writer_id = $1
`

func (q *Queries) DeleteAllRefreshTokens(ctx context.Context, grantWriterID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllRefreshTokens, grantWriterID)
	return err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const getRefreshTokenByTokenValue = `-- name: GetRefreshTokenByTokenValue :one
SELECT id, grant_writer_id, token, user_agent, ip_address, created_at, expires_at
FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetRefreshTokenByTokenValue(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByTokenValue, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantWriterID,
		&i.Token,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
