// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topics.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addTopicToClient = `-- name: AddTopicToClient :one
INSERT INTO clients_topics (topic_id, client_id)
VALUES ($1, $2)
RETURNING topic_id, client_id
`

type AddTopicToClientParams struct {
	TopicID  uuid.UUID `json:"topic_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) AddTopicToClient(ctx context.Context, arg AddTopicToClientParams) (ClientsTopic, error) {
	row := q.db.QueryRowContext(ctx, addTopicToClient, arg.TopicID, arg.ClientID)
	var i ClientsTopic
	err := row.Scan(&i.TopicID, &i.ClientID)
	return i, err
}

const addTopicToGrant = `-- name: AddTopicToGrant :execrows
INSERT INTO grants_topics (topic_id, grant_id)
SELECT $2, g.id
FROM grants g
WHERE g.id = $1
AND g.grant_writer_id = $3
`

type AddTopicToGrantParams struct {
	ID            uuid.UUID `json:"id"`
	TopicID       uuid.UUID `json:"topic_id"`
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
}

func (q *Queries) AddTopicToGrant(ctx context.Context, arg AddTopicToGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addTopicToGrant, arg.ID, arg.TopicID, arg.GrantWriterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (grant_writer_id, label)
VALUES ($1, $2)
RETURNING id, grant_writer_id, label
`

type CreateTopicParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	Label         string    `json:"label"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.GrantWriterID, arg.Label)
	var i Topic
	err := row.Scan(&i.ID, &i.GrantWriterID, &i.Label)
	return i, err
}

const deleteClientTopic = `-- name: DeleteClientTopic :exec
DELETE FROM clients_topics ct
USING topics t
WHERE ct.topic_id = t.id
AND ct.topic_id = $1
AND ct.client_id = $2
AND t.grant_writer_id = $3
`

type DeleteClientTopicParams struct {
	TopicID       uuid.UUID `json:"topic_id"`
	ClientID      uuid.UUID `json:"client_id"`
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
}

func (q *Queries) DeleteClientTopic(ctx context.Context, arg DeleteClientTopicParams) error {
	_, err := q.db.ExecContext(ctx, deleteClientTopic, arg.TopicID, arg.ClientID, arg.GrantWriterID)
	return err
}

const deleteGrantTopic = `-- name: DeleteGrantTopic :exec
DELETE FROM grants_topics gt
USING topics t
WHERE gt.topic_id = t.id
AND gt.topic_id = $1
AND gt.grant_id = $2
AND t.grant_writer_id = $3
`

type DeleteGrantTopicParams struct {
	TopicID       uuid.UUID `json:"topic_id"`
	GrantID       uuid.UUID `json:"grant_id"`
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
}

func (q *Queries) DeleteGrantTopic(ctx context.Context, arg DeleteGrantTopicParams) error {
	_, err := q.db.ExecContext(ctx, deleteGrantTopic, arg.TopicID, arg.GrantID, arg.GrantWriterID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
where id = $1
and grant_writer_id = $2
`

type DeleteTopicParams struct {
	ID            uuid.UUID `json:"id"`
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
}

func (q *Queries) DeleteTopic(ctx context.Context, arg DeleteTopicParams) error {
	_, err := q.db.ExecContext(ctx, deleteTopic, arg.ID, arg.GrantWriterID)
	return err
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, label
FROM topics
where grant_writer_id = $1
`

type GetAllTopicsRow struct {
	ID    uuid.UUID `json:"id"`
	Label string    `json:"label"`
}

func (q *Queries) GetAllTopics(ctx context.Context, grantWriterID uuid.UUID) ([]GetAllTopicsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTopics, grantWriterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTopicsRow
	for rows.Next() {
		var i GetAllTopicsRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTopicsByClient = `-- name: GetAllTopicsByClient :many
SELECT id, label
FROM clients_topics ct
JOIN topics t ON t.id=ct.topic_id
WHERE t.grant_writer_id = $1
AND ct.client_id = $2
`

type GetAllTopicsByClientParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	ClientID      uuid.UUID `json:"client_id"`
}

type GetAllTopicsByClientRow struct {
	ID    uuid.UUID `json:"id"`
	Label string    `json:"label"`
}

func (q *Queries) GetAllTopicsByClient(ctx context.Context, arg GetAllTopicsByClientParams) ([]GetAllTopicsByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTopicsByClient, arg.GrantWriterID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTopicsByClientRow
	for rows.Next() {
		var i GetAllTopicsByClientRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTopicsByGrant = `-- name: GetAllTopicsByGrant :many
SELECT id, label
FROM grants_topics gt
JOIN topics t ON t.id=gt.topic_id
WHERE t.grant_writer_id = $1
AND gt.grant_id = $2
`

type GetAllTopicsByGrantParams struct {
	GrantWriterID uuid.UUID `json:"grant_writer_id"`
	GrantID       uuid.UUID `json:"grant_id"`
}

type GetAllTopicsByGrantRow struct {
	ID    uuid.UUID `json:"id"`
	Label string    `json:"label"`
}

func (q *Queries) GetAllTopicsByGrant(ctx context.Context, arg GetAllTopicsByGrantParams) ([]GetAllTopicsByGrantRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTopicsByGrant, arg.GrantWriterID, arg.GrantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTopicsByGrantRow
	for rows.Next() {
		var i GetAllTopicsByGrantRow
		if err := rows.Scan(&i.ID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
